
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: antondzubak
    password: 123456
  main:
    banner-mode: off
server:
  port: 8085

